name: road_resq
description: "A real-time platform connecting vehicle owners — bikes, cars, and EVs —  with nearby mechanics and emergency service providers the moment they  need help most."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  go_router: ^14.0.0
  flutter_riverpod: ^2.5.1
  shared_preferences: ^2.5.5
  uuid: ^4.5.3
  image_picker: ^1.1.2
  geolocator: ^13.0.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo1.png"
  min_sdk_android: 21

  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/app_logo1.png
     - assets/images/app_logo2.png
