// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnBjFtSUwz3HeFXRz3CfjEKaCc15oVM54',
    appId: '1:362268567882:web:a17479008e3633622d79b3',
    messagingSenderId: '362268567882',
    projectId: 'roadresq-7c450',
    authDomain: 'roadresq-7c450.firebaseapp.com',
    storageBucket: 'roadresq-7c450.firebasestorage.app',
    measurementId: 'G-CSYB0GN5QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXQsywy7hY0Wk9e0gL6rxcNdlMO2Xkna8',
    appId: '1:362268567882:android:3da9503df767cf092d79b3',
    messagingSenderId: '362268567882',
    projectId: 'roadresq-7c450',
    storageBucket: 'roadresq-7c450.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoFLZw_iy8vZVMEPPoFCMThYy44e6pSHM',
    appId: '1:362268567882:ios:7700930620cb7a1d2d79b3',
    messagingSenderId: '362268567882',
    projectId: 'roadresq-7c450',
    storageBucket: 'roadresq-7c450.firebasestorage.app',
    iosBundleId: 'com.freshtechcreators.roadResq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoFLZw_iy8vZVMEPPoFCMThYy44e6pSHM',
    appId: '1:362268567882:ios:7700930620cb7a1d2d79b3',
    messagingSenderId: '362268567882',
    projectId: 'roadresq-7c450',
    storageBucket: 'roadresq-7c450.firebasestorage.app',
    iosBundleId: 'com.freshtechcreators.roadResq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnBjFtSUwz3HeFXRz3CfjEKaCc15oVM54',
    appId: '1:362268567882:web:b0380f3525254f592d79b3',
    messagingSenderId: '362268567882',
    projectId: 'roadresq-7c450',
    authDomain: 'roadresq-7c450.firebaseapp.com',
    storageBucket: 'roadresq-7c450.firebasestorage.app',
    measurementId: 'G-TDP6FXJ0PQ',
  );
}
